In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
import keras

import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv("HTRU_2.csv")
data.head()

Profile_mean  Profile_stdev  Profile_skewness  Profile_kurtosis   DM_mean  \
0    102.507812      58.882430          0.465318         -0.515088  1.677258   
1    103.015625      39.341649          0.323328          1.051164  3.121237   
2    136.750000      57.178449         -0.068415         -0.636238  3.642977   
3     88.726562      40.672225          0.600866          1.123492  1.178930   
4     93.570312      46.698114          0.531905          0.416721  1.636288   

    DM_stdev  DM_skewness  DM_kurtosis  class  
0  14.860146    10.576487   127.393580      0  
1  21.744669     7.735822    63.171909      0  
2  20.959280     6.896499    53.593661      0  
3  11.468720    14.269573   252.567306      0  
4  14.545074    10.621748   131.394004      0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17897 entries, 0 to 17896
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Profile_mean      17897 non-null  float64
 1   Profile_stdev     17897 non-null  float64
 2   Profile_skewness  17897 non-null  float64
 3   Profile_kurtosis  17897 non-null  float64
 4   DM_mean           17897 non-null  float64
 5   DM_stdev          17897 non-null  float64
 6   DM_skewness       17897 non-null  float64
 7   DM_kurtosis       17897 non-null  float64
 8   class             17897 non-null  int64  
dtypes: float64(8), int64(1)
memory usage: 1.2 MB


In [4]:
data.columns

Index(['Profile_mean', 'Profile_stdev', 'Profile_skewness', 'Profile_kurtosis',
       'DM_mean', 'DM_stdev', 'DM_skewness', 'DM_kurtosis', 'class'],
      dtype='object')

In [5]:
#data.drop(columns=["BodyTemp"],inplace=True)

In [6]:
data["class"].unique()

array([0, 1], dtype=int64)

In [7]:
#data["Age"].unique()

In [8]:
def plot_boxplot(data,ft):
    data.boxplot(column=[ft])
    plt.grid(False)
    plt.show()

In [9]:
def outliers(data,ft):
    Q1=data[ft].quantile(0.25)
    Q3=data[ft].quantile(0.75)
    IQR=Q3-Q1
    lower_bound=Q1-1.5*IQR
    upper_bound=Q3+1.5*IQR

    ls=data.index[ (data[ft] < lower_bound) | (data[ft]> upper_bound) ]

    return ls

In [10]:
index_list=[]
for feature in ["Profile_mean","Profile_stdev","Profile_skewness","Profile_kurtosis","DM_mean","DM_stdev","DM_skewness","DM_kurtosis"]:
    index_list.extend(outliers(data,feature))
index_list

[60,
 91,
 109,
 131,
 144,
 145,
 177,
 226,
 237,
 282,
 357,
 358,
 363,
 366,
 368,
 370,
 400,
 402,
 403,
 418,
 427,
 439,
 454,
 480,
 504,
 507,
 511,
 514,
 520,
 522,
 536,
 537,
 567,
 568,
 573,
 584,
 598,
 602,
 603,
 647,
 650,
 667,
 687,
 693,
 722,
 730,
 757,
 823,
 928,
 937,
 991,
 1027,
 1228,
 1233,
 1322,
 1330,
 1343,
 1375,
 1492,
 1513,
 1516,
 1544,
 1546,
 1555,
 1557,
 1561,
 1570,
 1584,
 1587,
 1604,
 1608,
 1620,
 1625,
 1628,
 1643,
 1655,
 1661,
 1662,
 1664,
 1666,
 1675,
 1683,
 1689,
 1702,
 1740,
 1747,
 1768,
 1833,
 1875,
 1977,
 2000,
 2024,
 2027,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2038,
 2041,
 2044,
 2047,
 2056,
 2057,
 2062,
 2073,
 2093,
 2102,
 2112,
 2180,
 2208,
 2216,
 2239,
 2253,
 2259,
 2342,
 2348,
 2369,
 2386,
 2388,
 2389,
 2403,
 2404,
 2413,
 2423,
 2452,
 2453,
 2468,
 2470,
 2475,
 2539,
 2556,
 2608,
 2610,
 2618,
 2625,
 2631,
 2656,
 2663,
 2670,
 2717,
 2718,
 2748,
 2751,
 2753,
 2757,
 2780,
 2788,
 27

In [11]:
def remove(data,ls):
    ls=sorted(set(ls))
    data=data.drop(ls)
    return data

In [12]:
data_cleaned=remove(data,index_list)

In [13]:
data_cleaned

Profile_mean  Profile_stdev  Profile_skewness  Profile_kurtosis  \
0        102.507812      58.882430          0.465318         -0.515088   
1        103.015625      39.341649          0.323328          1.051164   
2        136.750000      57.178449         -0.068415         -0.636238   
3         88.726562      40.672225          0.600866          1.123492   
4         93.570312      46.698114          0.531905          0.416721   
...             ...            ...               ...               ...   
17883    106.875000      47.571328          0.199440          0.284964   
17889    143.671875      45.302647         -0.045769          0.353643   
17891     96.000000      44.193113          0.388674          0.281344   
17892    136.429688      59.847421         -0.187846         -0.738123   
17895    114.507812      53.902400          0.201161         -0.024789   

        DM_mean   DM_stdev  DM_skewness  DM_kurtosis  class  
0      1.677258  14.860146    10.576487   127.393580      0  
1      3.121237  21.744669     7.735822    63.171909      0  
2      3.642977  20.959280     6.896499    53.593661      0  
3      1.178930  11.468720    14.269573   252.567306      0  
4      1.636288  14.545074    10.621748   131.394004      0  
...         ...        ...          ...          ...    ...  
17883  3.079431  20.984455     8.427475    78.259366      0  
17889  5.173913  26.462345     5.706651    33.802613      0  
17891  1.871237  15.833746     9.634927   104.821623      0  
17892  1.296823  12.166062    15.450260   285.931022      0  
17895  1.946488  13.381731    10.007967   134.238910      0  

[13320 rows x 9 columns]

In [14]:
data_cleaned.isnull().sum()

Profile_mean        0
Profile_stdev       0
Profile_skewness    0
Profile_kurtosis    0
DM_mean             0
DM_stdev            0
DM_skewness         0
DM_kurtosis         0
class               0
dtype: int64

In [15]:
#from scipy.stats import boxcox
#data_cleaned["Profile_kurtosis"],a=boxcox(data_cleaned["Profile_skewness"])

In [16]:
data_cleaned["class"].unique()

array([0, 1], dtype=int64)

In [17]:
X=data_cleaned.drop("class",axis=1)
y=data_cleaned["class"]

In [18]:
Train=[]
Test=[]
CV=[]
for i in range(0,101):
    from sklearn.model_selection import train_test_split
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)

    from sklearn.linear_model import LogisticRegression
    log_default=LogisticRegression()
    log_default.fit(X_train,y_train)

    ypred_train=log_default.predict(X_train)
    ypred_test=log_default.predict(X_test)

    from sklearn.metrics import accuracy_score
    Train.append(accuracy_score(y_train,ypred_train))
    Test.append(accuracy_score(y_test,ypred_test))

    from sklearn.model_selection import cross_val_score
    CV.append(cross_val_score(log_default,X_train,y_train,cv=5,scoring="accuracy").mean())

em=pd.DataFrame({"Train":Train,"Test":Test,"CV":CV})
gm=em[(abs(em["Train"]-em["Test"])<=0.05) & (abs(em["Test"]-em["CV"])<=0.05)]
rs=gm[gm["CV"]==gm["CV"].max()].index.to_list()[0]
print("Best random_state number:",rs)

Best random_state number: 44


In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=rs)

In [20]:
from sklearn.feature_selection import mutual_info_classif
mutual_info=mutual_info_classif(X_train,y_train)
mutual_info

array([0.00266402, 0.00027409, 0.00895697, 0.00415942, 0.0014301 ,
       0.00319087, 0.00194046, 0.00106671])

In [21]:
mutual_info=pd.Series(mutual_info)
mutual_info.index=X_train.columns
mutual_info.sort_values(ascending=False)

Profile_skewness    0.008957
Profile_kurtosis    0.004159
DM_stdev            0.003191
Profile_mean        0.002664
DM_skewness         0.001940
DM_mean             0.001430
DM_kurtosis         0.001067
Profile_stdev       0.000274
dtype: float64

In [22]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
ypred_train=log_reg.predict(X_train)

from sklearn.metrics import accuracy_score
print("Train accuracy:",accuracy_score(y_train,ypred_train))

from sklearn.model_selection import cross_val_score
print("CV Score:",cross_val_score(log_reg,X_train,y_train,cv=5,scoring="accuracy").mean())

ypred_test=log_reg.predict(X_test)
print("Test accuracy:",accuracy_score(y_test,ypred_test))

Train accuracy: 0.9899587087087087
CV Score: 0.9899587347676532
Test accuracy: 0.9842342342342343


In [23]:
from sklearn.neighbors import KNeighborsClassifier
estimator=KNeighborsClassifier()
param_grid={'n_neighbors':list(range(1,50))}

from sklearn.model_selection import GridSearchCV
knn_grid=GridSearchCV(estimator,param_grid,cv=5,scoring='accuracy')
knn_grid.fit(X_train,y_train)

knn_model=knn_grid.best_estimator_

y_pred_train=knn_model.predict(X_train)
y_pred_test=knn_model.predict(X_test)

from sklearn.metrics import accuracy_score
print("train accuracy:",accuracy_score(y_train,y_pred_train))
print("test accuracy:",accuracy_score(y_test,y_pred_test))

from sklearn.model_selection import cross_val_score
print("Cross Validation Score:",cross_val_score(knn_model,X_train,y_train,cv=5,scoring="accuracy").mean())

train accuracy: 0.9899587087087087
test accuracy: 0.9842342342342343
Cross Validation Score: 0.9899587347676532


In [61]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

estimator=SVC()
param_grid={'C':[0.01,0.1,1,10,100],'kernel':['linear','rbf','sigmoid','poly']}

svm_grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)
svm_grid.fit(X_train,y_train)

svm_model=svm_grid.best_estimator_

y_pred_train=svm_model.predict(X_train)
y_pred_test=svm_model.predict(X_test)

print("Train accuracy:",accuracy_score(y_train,ypred_train))
print("Cross validation score:",cross_val_score(svm_model,X_train,y_train,cv=5,scoring="accuracy").mean())
print("Test accuracy:",accuracy_score(y_test,ypred_test))

KeyboardInterrupt: 

In [24]:
from sklearn.tree import DecisionTreeClassifier
estimator=DecisionTreeClassifier(random_state=rs)
param_grid={"criterion":["gini","entropy"],
            "max_depth":list(range(1,16))}
from sklearn.model_selection import GridSearchCV
dt_grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)
dt_grid.fit(X_train,y_train)

dt=dt_grid.best_estimator_

dt_fi=dt.feature_importances_

index=[i for i,x in enumerate(dt_fi) if x>0]

X_train_dt=X_train.iloc[:,index]
X_test_dt=X_test.iloc[:,index]

dt.fit(X_train_dt,y_train)

ypred_train=dt.predict(X_train_dt)
ypred_test=dt.predict(X_test_dt)

print("Train Accuracy:",accuracy_score(y_train,ypred_train))
print("Cross validation score:",cross_val_score(dt,X_train_dt,y_train,cv=5,scoring="accuracy").mean())
print("Test accuracy:",accuracy_score(y_test,ypred_test))

Train Accuracy: 0.9907094594594594
Cross validation score: 0.9900525433980469
Test accuracy: 0.984984984984985


In [25]:
X_train_dt

Profile_skewness   DM_stdev
5434           0.209591  19.631579
17386         -0.271666  17.334127
10819          0.381744  24.109545
4122           0.129341  16.327731
281            0.351171  12.747101
...                 ...        ...
5475          -0.018614  19.410465
744           -0.176938  15.810420
12915          0.000311  27.259732
15060          0.475157  18.806904
4781           0.194430  15.512965

[10656 rows x 2 columns]

In [26]:
from sklearn.ensemble import RandomForestClassifier
estimator=RandomForestClassifier(random_state=rs)
param_grid={"n_estimators":list(range(1,51))}

from sklearn.model_selection import GridSearchCV
rf_grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)
rf_grid.fit(X_train,y_train)

rf=rf_grid.best_estimator_
rf_fi=rf.feature_importances_

index=[i for i,x in enumerate(rf_fi) if x>0]

X_train_rf=X_train.iloc[:,index]
X_test_rf=X_test.iloc[:,index]

rf.fit(X_train_rf,y_train)

ypred_train=rf.predict(X_train_rf)
ypred_test=rf.predict(X_test_rf)

print("Train Accuracy:",accuracy_score(y_train,ypred_train))
print("Cross validation score:",cross_val_score(rf,X_train_rf,y_train,cv=5,scoring="accuracy").mean())
print("Test accuracy:",accuracy_score(y_test,ypred_test))
            

Train Accuracy: 0.9977477477477478
Cross validation score: 0.9902403367426086
Test accuracy: 0.9846096096096096


In [27]:
from sklearn.ensemble import AdaBoostClassifier
estimator=AdaBoostClassifier(random_state=rs)
param_grid={"n_estimators":list(range(1,51))}

from sklearn.model_selection import GridSearchCV
ab_grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)
ab_grid.fit(X_train,y_train)

ab=ab_grid.best_estimator_
ab_fi=ab.feature_importances_

index=[i for i,x in enumerate(ab_fi) if x>0]

X_train_ab=X_train.iloc[:,index]
X_test_ab=X_test.iloc[:,index]

ab.fit(X_train_ab,y_train)

ypred_train=ab.predict(X_train_ab)
ypred_test=ab.predict(X_test_ab)

print("Train Accuracy:",accuracy_score(y_train,ypred_train))
print("Cross validation score:",cross_val_score(ab,X_train_ab,y_train,cv=5,scoring="accuracy").mean())
print("Test accuracy:",accuracy_score(y_test,ypred_test))

Train Accuracy: 0.9898648648648649
Cross validation score: 0.9899588668304833
Test accuracy: 0.9846096096096096


In [28]:
from sklearn.ensemble import GradientBoostingClassifier
estimator= GradientBoostingClassifier(random_state=rs)
param_grid={"n_estimators":list(range(1,10)),"learning_rate":[0.1,0.2,0.3,0.5,0.8,1]}

from sklearn.model_selection import GridSearchCV
gb_grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)
gb_grid.fit(X_train,y_train)

gb=gb_grid.best_estimator_
gb_fi=gb.feature_importances_

index=[i for i,x in enumerate(gb_fi) if x>0]

X_train_gb=X_train.iloc[:,index]
X_test_gb=X_test.iloc[:,index]

gb.fit(X_train_gb,y_train)

ypred_train=gb.predict(X_train_gb)
ypred_test=gb.predict(X_test_gb)

print("Train Accuracy:",accuracy_score(y_train,ypred_train))
print("Cross validation score:",cross_val_score(gb,X_train_gb,y_train,cv=5,scoring="accuracy").mean())
print("Test accuracy:",accuracy_score(y_test,ypred_test))
            

Train Accuracy: 0.990990990990991
Cross validation score: 0.989958734767653
Test accuracy: 0.9842342342342343


In [29]:
from xgboost import XGBClassifier
estimator= XGBClassifier(random_state=rs)
param_grid={"n_estimators":[10,20,40,100],"max_depth":[3,4,5],"gamma":[0,0.15,0.3,0.5,1]}

from sklearn.model_selection import GridSearchCV
xgb_grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)
xgb_grid.fit(X_train,y_train)

xgb=xgb_grid.best_estimator_
xgb_fi=xgb.feature_importances_

index=[i for i,x in enumerate(xgb_fi) if x>0]

X_train_xgb=X_train.iloc[:,index]
X_test_xgb=X_test.iloc[:,index]

xgb.fit(X_train_xgb,y_train)

ypred_train=xgb.predict(X_train_xgb)
ypred_test=xgb.predict(X_test_xgb)

print("Train Accuracy:",accuracy_score(y_train,ypred_train))
print("Cross validation score:",cross_val_score(xgb,X_train_xgb,y_train,cv=5,scoring="accuracy").mean())
print("Test accuracy:",accuracy_score(y_test,ypred_test))
            

Train Accuracy: 0.990990990990991
Cross validation score: 0.9902402927216652
Test accuracy: 0.9846096096096096


In [22]:
X

Profile_mean  Profile_stdev  Profile_skewness  Profile_kurtosis  \
0        102.507812      58.882430          0.465318         -0.515088   
1        103.015625      39.341649          0.323328          1.051164   
2        136.750000      57.178449         -0.068415         -0.636238   
3         88.726562      40.672225          0.600866          1.123492   
4         93.570312      46.698114          0.531905          0.416721   
...             ...            ...               ...               ...   
17883    106.875000      47.571328          0.199440          0.284964   
17889    143.671875      45.302647         -0.045769          0.353643   
17891     96.000000      44.193113          0.388674          0.281344   
17892    136.429688      59.847421         -0.187846         -0.738123   
17895    114.507812      53.902400          0.201161         -0.024789   

        DM_mean   DM_stdev  DM_skewness  DM_kurtosis  
0      1.677258  14.860146    10.576487   127.393580  
1      3.121237  21.744669     7.735822    63.171909  
2      3.642977  20.959280     6.896499    53.593661  
3      1.178930  11.468720    14.269573   252.567306  
4      1.636288  14.545074    10.621748   131.394004  
...         ...        ...          ...          ...  
17883  3.079431  20.984455     8.427475    78.259366  
17889  5.173913  26.462345     5.706651    33.802613  
17891  1.871237  15.833746     9.634927   104.821623  
17892  1.296823  12.166062    15.450260   285.931022  
17895  1.946488  13.381731    10.007967   134.238910  

[13320 rows x 8 columns]

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [35]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [36]:
from keras.models import Sequential
ann=Sequential()

In [37]:
from keras.layers import Dense

ann.add(Dense(input_dim=8,units=6,kernel_initializer="uniform",activation="relu"))
ann.add(Dense(units=6,kernel_initializer="uniform",activation="relu"))
ann.add(Dense(units=1,kernel_initializer="uniform",activation="sigmoid"))

ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [38]:
ann.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9698 - loss: 0.6544
Epoch 2/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9871 - loss: 0.5201
Epoch 3/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9879 - loss: 0.4176
Epoch 4/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9882 - loss: 0.3394
Epoch 5/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9880 - loss: 0.2803
Epoch 6/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9873 - loss: 0.2357
Epoch 7/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9886 - loss: 0.1986
Epoch 8/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9875 - loss: 0.1729
Epoch 9/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9875 - loss: 0.1513
Epoch 10/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9873 - loss: 0.1346
Epoch 11/100
333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9886 - loss: 0.1178
Epoch 12/100
333/333 ━━━━━━━━━━━━━━━━━━━━

In [39]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)

84/84 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score

print("Test Accuracy:",accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

Test Accuracy: 0.9906156156156156


array([[2639,    0],
       [  25,    0]], dtype=int64)

In [31]:
def build_cross_classifier():
    classifier=Sequential()
    classifier.add(Dense(input_dim=8,units=6,kernel_initializer="uniform",activation="relu"))
    classifier.add(Dense(units=6,kernel_initializer="uniform",activation="relu"))
    classifier.add(Dense(units=1,kernel_initializer="uniform",activation="sigmoid"))
    classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
    return classifier
    

In [32]:
estimator = KerasClassifier(build_cross_classifier())
param_grid = {'batch_size': (18,32), 'epochs': [50,100], "optimizer" :['adam', 'rmsprop']}

NameError: name 'KerasClassifier' is not defined

In [ ]:
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator,param_grid,scoring="accuracy",cv=5)

grid_result=grid.fit(X_train,y_train)

In [ ]:
grid_result.best_params_

In [ ]:
grid_result.best_score_